name: Unzip and Update Files

on:
  push:
    paths:
      - 'rooster.zip'  # Trigger the action only when rooster.zip is uploaded
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  unzip-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository to edit files

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Unzip the file
        run: |
          mkdir -p extracted_files
          unzip rooster.zip -d extracted_files  # Unzip the file to extracted_files

      - name: Copy extracted files to the root of the repository
        run: |
          cp -r extracted_files/* .  # Copy all files to the root of the repository

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update rooster files"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
